In [2]:
import pandas as pd
import numpy as np
import scipy.stats as st

In [3]:
# independence test - chi2 contigency
# pd.crosstab

In [4]:
survey = pd.read_excel(r"Survey_Corrected.xlsx")
survey.head(2)

Timestamp       1   2  \
0 2022-11-07 20:47:58.368  Female  34   
1 2022-11-07 20:57:41.684  Female  24   

                                                   3       4         5    6  \
0  Architecture,  civil engineering and related a...  Europe  Portugal  Yes   
1                                          Marketing  Europe  Portugal  Yes   

      7    8    9  ...  My work is/was not recognized  \
0  2014   No   No  ...                              0   
1  2019  Yes  Yes  ...                              0   

  I don’t/din't feel integrated in the organization/company  \
0                                                  0          
1                                                  0          

  I can/could not have a good life-work balance I am/was not paid enough  \
0                                             0                        0   
1                                             0                        1   

  I do/did not enjoy my job I do/did not have any guidance  \
0                         0                              0   
1                         1                              1   

  I do/did not feel great prospects of growing inside this company  \
0                                                  0                 
1                                                  1                 

  Other_negative_answer last_graduation_year experience_aft_gra  
0                    sd                 2014                  8  
1                     0                 2021                  1  

[2 rows x 40 columns]

In [5]:
# The questions are (corresponding to the numbers):
col_names1 = ['Timestamp',
 '1.  What is your gender?',
 '2. How old are you?',
 '3. What is the area of your studies at University?',
 '4. Where did you take the course?',
 '5. Please specify the country:',
 '6.  Have you completed your studies?',
 '7. In what year did you complete your degree?',
 '8. Did you take one second course in University?',
 '9. If yes, did you complete this second course?',
 '10. When did you complete this second course ?',
 '11. Does the search for your first job (after graduation) was easy?',
 '12. The experience of your first job was what you expected?',
 '13. Why?',
 '14. Did you feel the need to look for work abroad?',
 '15. Are you satisfied with the evolution of your career? ',
 '16. Select the options below that better fits your positive thoughts about your current or last work experience:',
 '17. Select the options below that better fits your negative thoughts about your current or last work experience:',
 '18. Do you feel that your University studies matches with what you aspirated?',
 '19. Did you take another specialization course/MBA/Phd/Bootcamp?',
 '20. If yes, what was the course/MBA/Phd/Bootcamp? And Why?',
 '21. Do you feel that you need/had to change career to have more work opportunities? ']

In [6]:
# Columns that were added
col_names2 = survey.iloc[:,22:].columns.values
col_names2

array(['I ‘m/was challenged everyday and I enjoy it.',
       'I have/had a good life-work balance', 'I have/had a fair salary',
       'I have/had freedom to work how I like',
       'I enjoy/enjoyed  my work',
       'I feel/felt stimulated and well guided in the beginning',
       'Other_positive_answer', 'I ‘m/was not challenged everyday',
       'My work is/was not recognized',
       "I don’t/din't feel integrated in the organization/company",
       'I can/could not have a good life-work balance',
       'I am/was not paid enough', 'I do/did not enjoy my job',
       'I do/did not have any guidance',
       'I do/did not feel great prospects of growing inside this company',
       'Other_negative_answer', 'last_graduation_year',
       'experience_aft_gra'], dtype=object)

In [7]:
survey[14].value_counts()

Yes.  But I stayed in my country.               16
No.                                             13
Yes.  And I went to work in another country.    12
Name: 14, dtype: int64

In [8]:
# Correlação entre das colunas e ver se estas são independentes 
#         Pais   Oppo
# x -  20        10
# y - 

In [9]:
# HYPOTHESIS

# 1 - H0 NOT REJECTED
# H0: people satisfied with 1st job [12] INDEPENDENT looking work abroad [14] 
# H1: people satisfied with 1st job [12] DEPENDENT looking work abroad [14] 

# 2 - H0 NOT REJECTED
# H0: career evolution satisfaction [15] INDEPENDENT working abroad [14]
# H1: career evolution satisfaction [15] DEPENDENT working abroad [14]

# 3 - H0 NOT REJECTED
# H0: career evolution satisfaction [15] INDEPENDENT aspirations [18]
# H1: career evolution satisfaction [15] INDEPENDENT aspirations [18]

# 4 - *** H0 REJECTED ***
# H0: career evolution satisfaction [15] INDEPENDENT taking another course/MBA/Phd/Bootcamp [19]
# H1: career evolution satisfaction [15] DEPENDENT taking another course/MBA/Phd/Bootcamp [19]

# 5 - H0 NOT REJECTED
# H0: career evolution satisfaction [15] INDEPENDENT changing career for more opportunities [21]
# H1: career evolution satisfaction [15] DEPENDENT changing career for more opportunities [21]

# 6 - H0 NOT REJECTED
# H0: area of university studies [3] INDEPENDENT taking another course/MBA/Phd/Bootcamp in different area [19]
# H1: area of university studies DEPENDENT taking another course/MBA/Phd/Bootcamp in different area [19]

# 7 - H0 NOT REJECTED
# H0: areas of study [3] INDEPENDENT career evolution [15]
# H1: areas of study [3] DEPENDENT career evolution [15]

# 8 - H0 NOT REJECTED
# H0: career evolution [15] INDEPENDENT Countries [5] 
# H1: career evolution [15] DEPENDENT Countries [5]

# 9 - H0 NOT REJECTED
# H0: Opportunities perception by changing career [21] INDEPENDENT Countries [5]
# H1: Opportunities perception by changing career [21] DEPENDENT Countries [5]

# 10 - H0 NOT REJECTED
# H0: working experience ['experience_aft_gra'] INDEPENDENT career evolution [15] 
# H1: working experience ['experience_aft_gra'] INDEPENDENT career evolution [15] 

# 11 - H0 NOT REJECTED
# H0: working experience ['experience_aft_gra'] INDEPENDENT career evolution [15] in Portugal
# H1: working experience ['experience_aft_gra'] INDEPENDENT career evolution [15] in Portugal

# 12 - H0 NOT REJECTED
# H0: people satisfied with 1st job [12] INDEPENDENT country
# H1: people satisfied with 1st job [12] DEPENDENT country

# working expirience ~ others

# satisfied with their first job ['Yes' in 12]

#  didn't look for work abroad nor think about it ['No' in 14]

#   are satisfied with the evolution of the career ['Yes' 15]  

#  feel that University studies matches with what they aspirated ['Yes' in 18]

#  better and more work opportunities ['No' or 'Not necessarily' in 21]

# How work more time are more or less satisfaied



In [10]:
survey[5].value_counts()

Portugal           21
Brazil              2
United States       2
United Kingdom      2
Usa                 2
Colombia            1
South Africa        1
Uk                  1
Ireland             1
Austria             1
Denmark             1
Egypt               1
Australia           1
Canada              1
China               1
New Zealand         1
The Netherlands     1
Name: 5, dtype: int64

In [11]:
survey[21].value_counts()

Yes                23
Not necessarily    10
No                  8
Name: 21, dtype: int64

# 1 Hypotese

In [12]:
# 1) SET THE HYPOTHESIS
# H0: people satisfied with 1st job [12] INDEPENDENT looking work abroad [14] 
# H1: people satisfied with 1st job [12] DEPENDENT looking work abroad [14] 


# 2) CHOOSE THE SIGNIFICANCE LEVEL
alpha = 0.05
print("The significance level is: ", alpha)

# 3) SAMPLE
corr_1job_abroad = pd.crosstab(survey[12], survey[14], dropna=False)

# 4) and 5) COMPUTE THE STATISTICS and COMPUTE THE p-value:
st.chi2_contingency(corr_1job_abroad) 


The significance level is:  0.05


(2.7061307754242536,
 0.25844680548158955,
 2,
 array([[7.29268293, 6.73170732, 8.97560976],
        [5.70731707, 5.26829268, 7.02439024]]))

In [13]:
# 6) DECISION

p_value = 0.25844680548158955
p_value < alpha

# I do not reject the H0. It seems like with 0.05 of confidence level that people satisfied with this 1st job [12] can or can't look to work abroad [14].

False

In [14]:
# NOW WITH 'YES's TOGETHER

survey[14_2]=survey[14]
for i in range(len(survey[14])):
    if survey[14_2][i]=="No.":
        survey[14_2][i] = "No"
    else:
        survey[14_2][i] = "Yes"

C:\Users\inesa\AppData\Local\Temp\ipykernel_9124\1620908967.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  survey[14_2][i] = "Yes"
C:\Users\inesa\AppData\Local\Temp\ipykernel_9124\1620908967.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  survey[14_2][i] = "No"


In [15]:
# 1) SET THE HYPOTHESIS
# H0: people satisfied with 1st job [12] INDEPENDENT looking work abroad [14] 
# H1: people satisfied with 1st job [12] DEPENDENT looking work abroad [14] 


# 2) CHOOSE THE SIGNIFICANCE LEVEL
alpha = 0.05
print("The significance level is: ", alpha)

# 3) SAMPLE
corr_1job_abroad = pd.crosstab(survey[12], survey[14_2], dropna=False)
corr_1job_abroad

The significance level is:  0.05


142  No  Yes
12          
No    5   18
Yes   8   10

In [16]:
# 4) and 5) COMPUTE THE STATISTICS and COMPUTE THE p-value:
st.chi2_contingency(corr_1job_abroad) 

(1.4697951505016726,
 0.22537801711617175,
 1,
 array([[ 7.29268293, 15.70731707],
        [ 5.70731707, 12.29268293]]))

In [17]:
# 6) DECISION

p_value = 0.22537801711617175
p_value < alpha

# (p_value < alpha --> False) 
# I do not reject the H0. It seems like with 0.05 of confidence level that people satisfied with this 1st job [12] can or can't look to work abroad [14].

False

# 2 Hypotese

In [76]:
# People who went to work abroad
survey['14_abroad']=survey[14]
for i in range(len(survey[14])):
    if "another country" in survey["14_abroad"][i]:
        survey["14_abroad"][i] = "Work_Abroad"
    else:
        survey["14_abroad"][i] = "No"

C:\Users\inesa\AppData\Local\Temp\ipykernel_9124\4178542563.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  survey["14_abroad"][i] = "Work_Abroad"
C:\Users\inesa\AppData\Local\Temp\ipykernel_9124\4178542563.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  survey["14_abroad"][i] = "No"


In [77]:
# 1) SET THE HYPOTHESIS
# H0: career evolution satisfection [15] INDEPENDENT working abroad [14_abroad]
# H1: career evolution satisfection [15] DEPENDENT working abroad [14_abroad]

# 2) CHOOSE THE SIGNIFICANCE LEVEL
alpha = 0.05
print("The significance level is: ", alpha)

# 3) SAMPLE
corr_sat_abroad = pd.crosstab(survey[15], survey["14_abroad"], dropna=False)
corr_sat_abroad

The significance level is:  0.05


14_abroad  No  Work_Abroad
15                        
No         12            3
Yes        16           10

In [78]:
# 4) and 5) COMPUTE THE STATISTICS and COMPUTE THE p-value:
st.chi2_contingency(corr_sat_abroad) 

(0.7660062693716541,
 0.3814553874840535,
 1,
 array([[10.24390244,  4.75609756],
        [17.75609756,  8.24390244]]))

In [21]:
# 6) DECISION

p_value = 0.3814553874840535
p_value < alpha

# (p_value < alpha --> False) 
# I do not reject the H0. It seems like with 0.05 of confidence level that
        # people satisfisfaction with the evolution of the career doens't affect if they search for work abroad

False

In [22]:
#correction
survey[survey[5] == 'Colombia']

Timestamp       1   2  \
19 2022-11-08 14:48:14.578  Female  25   

                                          3              4         5    6  \
19  Business, management and administration  South America  Colombia  Yes   

       7    8    9  ...  I can/could not have a good life-work balance  \
19  2020  Yes  Yes  ...                                              0   

   I am/was not paid enough I do/did not enjoy my job  \
19                        1                         0   

   I do/did not have any guidance  \
19                              0   

   I do/did not feel great prospects of growing inside this company  \
19                                                  0                 

   Other_negative_answer last_graduation_year experience_aft_gra  142  \
19                     0                 2020                  2  Yes   

   14_abroad  
19        No  

[1 rows x 42 columns]

In [23]:
survey.loc[19,14] = "Yes. And I went to work in another country."

# 3 Hypotese

In [24]:
print(col_names1[15])
print(col_names1[18])

15. Are you satisfied with the evolution of your career? 
18. Do you feel that your University studies matches with what you aspirated?


In [25]:
survey[[15,18]].value_counts()

15   18 
Yes  No     18
No   No     10
Yes  Yes     8
No   Yes     5
dtype: int64

In [26]:
# 1) SET THE HYPOTHESIS
# H0: career evolution satisfection INDEPENDENT aspirations [18]
# H1: career evolution satisfection INDEPENDENT aspirations [18]

# 2) CHOOSE THE SIGNIFICANCE LEVEL
alpha = 0.05
print("The significance level is: ", alpha)

# 3) SAMPLE
corr_career_aspirations = pd.crosstab(survey[15], survey[18], dropna=False)
corr_career_aspirations

The significance level is:  0.05


18   No  Yes
15          
No   10    5
Yes  18    8

In [27]:
# 4) and 5) COMPUTE THE STATISTICS and COMPUTE THE p-value:
st.chi2_contingency(corr_career_aspirations) 

(0.0,
 1.0,
 1,
 array([[10.24390244,  4.75609756],
        [17.75609756,  8.24390244]]))

In [28]:
# 6) DECISION

p_value = 1.0
p_value < alpha

# (p_value < alpha --> False) 
# I do not reject the H0. It seems like with 0.05 of confidence level that
        # the career evolution satisfection isn't affected with what people aspirated in life
        

False

# 4 Hypothese

In [29]:
print(col_names1[15])
print(col_names1[19])

15. Are you satisfied with the evolution of your career? 
19. Did you take another specialization course/MBA/Phd/Bootcamp?


In [30]:
survey[[15,19]].value_counts()

15   19                                                 
Yes  Yes. The specialization was/is in a different area.    15
     No                                                      8
No   No                                                      7
     Yes. The specialization was/is in the same area.        5
     Yes. The specialization was/is in a different area.     3
Yes  Yes. The specialization was/is in the same area.        3
dtype: int64

In [31]:
# 1) SET THE HYPOTHESIS
# H0: career evolution satisfection [15] INDEPENDENT taking another course/MBA/Phd/Bootcamp [19]
# H1: career evolution satisfection [15] DEPENDENT taking another course/MBA/Phd/Bootcamp [19]

# 2) CHOOSE THE SIGNIFICANCE LEVEL
alpha = 0.05
print("The significance level is: ", alpha)

# 3) SAMPLE
corr_career_bootcamp = pd.crosstab(survey[15], survey[19], dropna=False)
corr_career_bootcamp

The significance level is:  0.05


19   No  Yes. The specialization was/is in a different area.  \
15                                                             
No    7                                                  3     
Yes   8                                                 15     

19   Yes. The specialization was/is in the same area.  
15                                                     
No                                                  5  
Yes                                                 3

In [32]:
# 4) and 5) COMPUTE THE STATISTICS and COMPUTE THE p-value:
st.chi2_contingency(corr_career_bootcamp) 

(6.051004273504273,
 0.04853344472403861,
 2,
 array([[ 5.48780488,  6.58536585,  2.92682927],
        [ 9.51219512, 11.41463415,  5.07317073]]))

In [33]:
# 6) DECISION

p_value = 0.04853344472403861
p_value < alpha

# (p_value < alpha --> TRUE) 
# I REJECT HO. It seems like with 0.05 of confidence level that
        # the career evolution satisfection have some correlation with the fact that people take another course/MBA/Phd/Bootcamp

True

# 5 Hypothese

In [34]:
print(col_names1[15])
print(col_names1[21])

15. Are you satisfied with the evolution of your career? 
21. Do you feel that you need/had to change career to have more work opportunities? 


In [35]:
# 1) SET THE HYPOTHESIS
# H0: career evolution satisfection [15] INDEPENDENT changing career for more opportunities [21]
# H1: career evolution satisfection [15] DEPENDENT changing career for more opportunities [21]

# 2) CHOOSE THE SIGNIFICANCE LEVEL
alpha = 0.05
print("The significance level is: ", alpha)

# 3) SAMPLE
corr_career_opportunities = pd.crosstab(survey[15], survey[21], dropna=False)
corr_career_opportunities

The significance level is:  0.05


21   No  Not necessarily  Yes
15                           
No    2                3   10
Yes   6                7   13

In [36]:
# 4) and 5) COMPUTE THE STATISTICS and COMPUTE THE p-value:
st.chi2_contingency(corr_career_opportunities) 

(1.1207580824972132,
 0.5709925930803051,
 2,
 array([[ 2.92682927,  3.65853659,  8.41463415],
        [ 5.07317073,  6.34146341, 14.58536585]]))

In [37]:
# 6) DECISION

p_value =  0.5709925930803051
p_value < alpha

# (p_value < alpha --> False) 
# I do not reject the H0. It seems like with 0.05 of confidence level that
        # career evolution satisfection is independent of changing the career

False

In [38]:
# And if aggregate the 'No' with the 'Not necessarily'

survey['21_agg_no']=survey[21]
for i in range(len(survey[21])):
    if "necessarily" in survey["21_agg_no"][i]:
        survey["21_agg_no"][i] = "No"
    else:
        pass

C:\Users\inesa\AppData\Local\Temp\ipykernel_9124\2474946180.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  survey["21_agg_no"][i] = "No"


In [39]:
corr_career_opportunities = pd.crosstab(survey[15], survey["21_agg_no"], dropna=False)
corr_career_opportunities

21_agg_no  No  Yes
15                
No          5   10
Yes        13   13

In [40]:
st.chi2_contingency(corr_career_opportunities) 

(0.5028505512201167,
 0.47825028537849756,
 1,
 array([[ 6.58536585,  8.41463415],
        [11.41463415, 14.58536585]]))

In [41]:
p_value =  0.47825028537849756
p_value < alpha

# (p_value < alpha --> False) 
# I do not reject the H0. It seems like with 0.05 of confidence level that
        # career evolution satisfection is independent of changing the career

False

# 6 Hypothese

In [42]:
print(col_names1[3])
print(col_names1[19])

3. What is the area of your studies at University?
19. Did you take another specialization course/MBA/Phd/Bootcamp?


In [43]:
# 1) SET THE HYPOTHESIS
# H0: area of university studies [3] INDEPENDENT taking another course/MBA/Phd/Bootcamp in different area [19]
# H1: area of university studies [3] DEPENDENT taking another course/MBA/Phd/Bootcamp in different area [19]

# 2) CHOOSE THE SIGNIFICANCE LEVEL
alpha = 0.05
print("The significance level is: ", alpha)

# 3) SAMPLE
corr_area_bootcamp = pd.crosstab(survey[3], survey[19], dropna=False)
corr_area_bootcamp

The significance level is:  0.05


19                                                  No  \
3                                                        
Architecture,  civil engineering and related areas   0   
Arts, culture and entertainment                      2   
Business, management and administration              3   
Communications                                       1   
Health and medicine                                  1   
IT                                                   1   
Industry and food industry                           1   
Law and public policy                                1   
Marketing                                            1   
Other                                                2   
Science, engineering and related areas               2   

19                                                  Yes. The specialization was/is in a different area.  \
3                                                                                                         
Architecture,  civil engineering and related areas                                                  3     
Arts, culture and entertainment                                                                     2     
Business, management and administration                                                             4     
Communications                                                                                      0     
Health and medicine                                                                                 2     
IT                                                                                                  0     
Industry and food industry                                                                          1     
Law and public policy                                                                               1     
Marketing                                                                                           3     
Other                                                                                               1     
Science, engineering and related areas                                                              1     

19                                                  Yes. The specialization was/is in the same area.  
3                                                                                                     
Architecture,  civil engineering and related areas                                                 1  
Arts, culture and entertainment                                                                    1  
Business, management and administration                                                            1  
Communications                                                                                     0  
Health and medicine                                                                                1  
IT                                                                                                 0  
Industry and food industry                                                                         2  
Law and public policy                                                                              0  
Marketing                                                                                          0  
Other                                                                                              1  
Science, engineering and related areas                                                             1

In [44]:
corr_dif_area_bootcamp = (corr_area_bootcamp.reset_index().iloc[:,:-1]).set_index(3)
corr_dif_area_bootcamp

19                                                  No  \
3                                                        
Architecture,  civil engineering and related areas   0   
Arts, culture and entertainment                      2   
Business, management and administration              3   
Communications                                       1   
Health and medicine                                  1   
IT                                                   1   
Industry and food industry                           1   
Law and public policy                                1   
Marketing                                            1   
Other                                                2   
Science, engineering and related areas               2   

19                                                  Yes. The specialization was/is in a different area.  
3                                                                                                        
Architecture,  civil engineering and related areas                                                  3    
Arts, culture and entertainment                                                                     2    
Business, management and administration                                                             4    
Communications                                                                                      0    
Health and medicine                                                                                 2    
IT                                                                                                  0    
Industry and food industry                                                                          1    
Law and public policy                                                                               1    
Marketing                                                                                           3    
Other                                                                                               1    
Science, engineering and related areas                                                              1

In [45]:
# 4) and 5) COMPUTE THE STATISTICS and COMPUTE THE p-value:
st.chi2_contingency(corr_dif_area_bootcamp) 

(6.927380952380951,
 0.7322823952105314,
 10,
 array([[1.36363636, 1.63636364],
        [1.81818182, 2.18181818],
        [3.18181818, 3.81818182],
        [0.45454545, 0.54545455],
        [1.36363636, 1.63636364],
        [0.45454545, 0.54545455],
        [0.90909091, 1.09090909],
        [0.90909091, 1.09090909],
        [1.81818182, 2.18181818],
        [1.36363636, 1.63636364],
        [1.36363636, 1.63636364]]))

In [46]:
# 6) DECISION

p_value =  0.7322823952105314
p_value < alpha

# (p_value < alpha --> False) 
# I do not reject the H0. It seems like with 0.05 of confidence level that
        # the area of university studies doens't have influence choosing a different area for another course/MBA/Phd/Bootcamp [19]

False

# 7. Hypothese

In [47]:
print(col_names1[3])
print(col_names1[15])

3. What is the area of your studies at University?
15. Are you satisfied with the evolution of your career? 


In [48]:
# 1) SET THE HYPOTHESIS
# H0: areas of studie [3] INDEPENDENT career evolution satisfaction [15]
# H1: areas of studie [3] DEPENDENT career evolution satisfaction [15]

# 2) CHOOSE THE SIGNIFICANCE LEVEL
alpha = 0.05
print("The significance level is: ", alpha)

# 3) SAMPLE
corr_area_evolution = pd.crosstab(survey[3], survey[15], dropna=False)
corr_area_evolution

The significance level is:  0.05


15                                                  No  Yes
3                                                          
Architecture,  civil engineering and related areas   2    2
Arts, culture and entertainment                      2    3
Business, management and administration              1    7
Communications                                       1    0
Health and medicine                                  2    2
IT                                                   1    0
Industry and food industry                           1    3
Law and public policy                                1    1
Marketing                                            1    3
Other                                                1    3
Science, engineering and related areas               2    2

In [49]:
# 4) and 5) COMPUTE THE STATISTICS and COMPUTE THE p-value:
st.chi2_contingency(corr_area_evolution) 

(7.272243589743589,
 0.6995177383001153,
 10,
 array([[1.46341463, 2.53658537],
        [1.82926829, 3.17073171],
        [2.92682927, 5.07317073],
        [0.36585366, 0.63414634],
        [1.46341463, 2.53658537],
        [0.36585366, 0.63414634],
        [1.46341463, 2.53658537],
        [0.73170732, 1.26829268],
        [1.46341463, 2.53658537],
        [1.46341463, 2.53658537],
        [1.46341463, 2.53658537]]))

In [50]:
# 6) DECISION

p_value = 0.6995177383001153
p_value < alpha

# (p_value < alpha --> False) 
# I do not reject the H0. It seems like with 0.05 of confidence level that
        # the differente academic areas does not influence with career evolution satisfaction

False

# 8 Hypothese

In [51]:
print(col_names1[15])
print(col_names1[5])

15. Are you satisfied with the evolution of your career? 
5. Please specify the country:


In [52]:
# Join all countries but Portugal in '5_Others'

survey['5_Others']=survey[5]
for i in range(len(survey[5])):
    if "Portugal" in survey["5_Others"][i]:
        pass
    else:
        survey["5_Others"][i] = 'Others'

C:\Users\inesa\AppData\Local\Temp\ipykernel_9124\3804152810.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  survey["5_Others"][i] = 'Others'


In [53]:
# 1) SET THE HYPOTHESIS
# H0: career evolution satisfaction [15] INDEPENDENT Countries [5] 
# H1: career evolution satisfaction [15] DEPENDENT Countries [5]

# 2) CHOOSE THE SIGNIFICANCE LEVEL
alpha = 0.05
print("The significance level is: ", alpha)

# 3) SAMPLE
corr_carerr_country = pd.crosstab(survey[15], survey["5_Others"], dropna=False)
corr_carerr_country

The significance level is:  0.05


5_Others  Others  Portugal
15                        
No             6         9
Yes           14        12

In [54]:
# 4) and 5) COMPUTE THE STATISTICS and COMPUTE THE p-value:
st.chi2_contingency(corr_carerr_country) 

(0.28090506715506713,
 0.5961086164332364,
 1,
 array([[ 7.31707317,  7.68292683],
        [12.68292683, 13.31707317]]))

In [55]:
# 6) DECISION

p_value = 0.5961086164332364
p_value < alpha

# (p_value < alpha --> False) 
# I do not reject the H0. It seems like with 0.05 of confidence level that
        # the career evolution satisfaction isn't related where do people have your studies 

False

# 9 Hypothese

In [56]:
print(col_names1[21])
print(col_names1[5])

21. Do you feel that you need/had to change career to have more work opportunities? 
5. Please specify the country:


In [57]:
# 1) SET THE HYPOTHESIS
# H0: Opportunities perception by changing career [21] INDEPENDENT Countries [5]
# H1: Opportunities perception by changing career [21] DEPENDENT Countries [5]

# 2) CHOOSE THE SIGNIFICANCE LEVEL
alpha = 0.05
print("The significance level is: ", alpha)

# 3) SAMPLE
corr_oppotunities_country = pd.crosstab(survey["21_agg_no"], survey["5_Others"], dropna=False)
corr_oppotunities_country

The significance level is:  0.05


5_Others   Others  Portugal
21_agg_no                  
No              9         9
Yes            11        12

In [58]:
# 4) and 5) COMPUTE THE STATISTICS and COMPUTE THE p-value:
st.chi2_contingency(corr_oppotunities_country) 

(0.0,
 1.0,
 1,
 array([[ 8.7804878,  9.2195122],
        [11.2195122, 11.7804878]]))

In [59]:
# 6) DECISION

p_value = 1
p_value < alpha

# (p_value < alpha --> False) 
# I do not reject the H0. It seems like with 0.05 of confidence level that
        # getting more work opportunities perception by changing career is not influenced by the country where the people took their courses

False

# 10 Hyphotese

In [60]:
print(col_names1[15])

15. Are you satisfied with the evolution of your career? 


In [61]:
# 1) SET THE HYPOTHESIS
# H0: working experience ['experience_aft_gra'] INDEPENDENT career evolution [15] 
# H1: working experience ['experience_aft_gra'] INDEPENDENT career evolution [15] 

# 2) CHOOSE THE SIGNIFICANCE LEVEL
alpha = 0.05
print("The significance level is: ", alpha)

# 3) SAMPLE
corr_work_exp_career = pd.crosstab(survey["experience_aft_gra"], survey[15], dropna=False)
corr_work_exp_career

The significance level is:  0.05


15                  No  Yes
experience_aft_gra         
0                    1    5
1                    3    3
2                    1    3
3                    2    5
5                    1    0
6                    1    2
8                    3    3
9                    1    3
11                   1    0
13                   0    1
14                   0    1
33                   1    0

In [62]:
# 4) and 5) COMPUTE THE STATISTICS and COMPUTE THE p-value:
st.chi2_contingency(corr_work_exp_career) 

(8.980952380952381,
 0.6236505934412817,
 11,
 array([[2.19512195, 3.80487805],
        [2.19512195, 3.80487805],
        [1.46341463, 2.53658537],
        [2.56097561, 4.43902439],
        [0.36585366, 0.63414634],
        [1.09756098, 1.90243902],
        [2.19512195, 3.80487805],
        [1.46341463, 2.53658537],
        [0.36585366, 0.63414634],
        [0.36585366, 0.63414634],
        [0.36585366, 0.63414634],
        [0.36585366, 0.63414634]]))

In [63]:
# 6) DECISION

p_value = 0.6236505934412817
p_value < alpha

# (p_value < alpha --> False) 
# I do not reject the H0. It seems like with 0.05 of confidence level that
        # the working experience is independent from the career evolution satisfaction 


False

# 11 Hypothese

In [64]:
print(col_names1[15])
print(col_names1[5])

15. Are you satisfied with the evolution of your career? 
5. Please specify the country:


In [65]:
#creating a survey only with the values from Portugal
survey_pt = survey[survey["5_Others"] == "Portugal"]

In [66]:
# 1) SET THE HYPOTHESIS
# H0: working experience ['experience_aft_gra'] INDEPENDENT career evolution satisfaction [15] in Portugal 
# H1: working experience ['experience_aft_gra'] INDEPENDENT career evolution satisfaction [15] in Portugal

# 2) CHOOSE THE SIGNIFICANCE LEVEL
alpha = 0.05
print("The significance level is: ", alpha)

# 3) SAMPLE
corr_work_exp_career_pt = pd.crosstab(survey_pt["experience_aft_gra"], survey_pt[15], dropna=False)
corr_work_exp_career_pt

The significance level is:  0.05


15                  No  Yes
experience_aft_gra         
0                    0    1
1                    1    3
2                    1    0
3                    2    3
6                    1    1
8                    2    1
9                    1    2
13                   0    1
33                   1    0

In [67]:
# 4) and 5) COMPUTE THE STATISTICS and COMPUTE THE p-value:
st.chi2_contingency(corr_work_exp_career_pt) 

(5.551388888888889,
 0.6973401279896991,
 8,
 array([[0.42857143, 0.57142857],
        [1.71428571, 2.28571429],
        [0.42857143, 0.57142857],
        [2.14285714, 2.85714286],
        [0.85714286, 1.14285714],
        [1.28571429, 1.71428571],
        [1.28571429, 1.71428571],
        [0.42857143, 0.57142857],
        [0.42857143, 0.57142857]]))

In [68]:
# 6) DECISION

p_value = 0.6973401279896991
p_value < alpha

# (p_value < alpha --> False) 
# I do not reject the H0. It seems like with 0.05 of confidence level that
        # the working experience is independent from the career evolution satisfaction in Portugal

False

# 12 Hypothese

In [69]:
print(col_names1[12])
print(col_names1[5])

12. The experience of your first job was what you expected?
5. Please specify the country:


In [70]:
# 1) SET THE HYPOTHESIS
# H0: people satisfied with 1st job [12] INDEPENDENT country [5]
# H1: people satisfied with 1st job [12] DEPENDENT country [5]

# 2) CHOOSE THE SIGNIFICANCE LEVEL
alpha = 0.05
print("The significance level is: ", alpha)

# 3) SAMPLE
corr_1st_country = pd.crosstab(survey[5], survey[12], dropna=False)
corr_1st_country

The significance level is:  0.05


12               No  Yes
5                       
Australia         1    0
Austria           0    1
Brazil            2    0
Canada            1    0
China             0    1
Colombia          1    0
Denmark           1    0
Egypt             0    1
Ireland           1    0
New Zealand       0    1
Portugal         11   10
South Africa      1    0
The Netherlands   0    1
Uk                0    1
United Kingdom    2    0
United States     1    1
Usa               1    1

In [71]:
# 4) and 5) COMPUTE THE STATISTICS and COMPUTE THE p-value:
st.chi2_contingency(corr_1st_country) 

(15.670922475270302,
 0.4761543956276749,
 16,
 array([[ 0.56097561,  0.43902439],
        [ 0.56097561,  0.43902439],
        [ 1.12195122,  0.87804878],
        [ 0.56097561,  0.43902439],
        [ 0.56097561,  0.43902439],
        [ 0.56097561,  0.43902439],
        [ 0.56097561,  0.43902439],
        [ 0.56097561,  0.43902439],
        [ 0.56097561,  0.43902439],
        [ 0.56097561,  0.43902439],
        [11.7804878 ,  9.2195122 ],
        [ 0.56097561,  0.43902439],
        [ 0.56097561,  0.43902439],
        [ 0.56097561,  0.43902439],
        [ 1.12195122,  0.87804878],
        [ 1.12195122,  0.87804878],
        [ 1.12195122,  0.87804878]]))

In [72]:
# 6) DECISION

p_value = 0.4761543956276749
p_value < alpha

# (p_value < alpha --> False) 
# I do not reject the H0. It seems like with 0.05 of confidence level that
        # people satisfied with 1st job is independent from the country where they have studied

False

In [80]:
col_names1

['Timestamp',
 '1.  What is your gender?',
 '2. How old are you?',
 '3. What is the area of your studies at University?',
 '4. Where did you take the course?',
 '5. Please specify the country:',
 '6.  Have you completed your studies?',
 '7. In what year did you complete your degree?',
 '8. Did you take one second course in University?',
 '9. If yes, did you complete this second course?',
 '10. When did you complete this second course ?',
 '11. Does the search for your first job (after graduation) was easy?',
 '12. The experience of your first job was what you expected?',
 '13. Why?',
 '14. Did you feel the need to look for work abroad?',
 '15. Are you satisfied with the evolution of your career? ',
 '16. Select the options below that better fits your positive thoughts about your current or last work experience:',
 '17. Select the options below that better fits your negative thoughts about your current or last work experience:',
 '18. Do you feel that your University studies matches wit

In [81]:
survey.rename(columns={1:'1.  What is your gender?',
 2:'2. How old are you?',
 3:'3. What is the area of your studies at University?',
 4:'4. Where did you take the course?',
 5:'5. Please specify the country:',
 6:'6.  Have you completed your studies?',
 7:'7. In what year did you complete your degree?',
 8:'8. Did you take one second course in University?',
 9:'9. If yes, did you complete this second course?',
 10:'10. When did you complete this second course ?',
 11:'11. Does the search for your first job (after graduation) was easy?',
 12:'12. The experience of your first job was what you expected?',
 13:'13. Why?',
 14:'14. Did you feel the need to look for work abroad?',
 15:'15. Are you satisfied with the evolution of your career? ',
 16:'16. Select the options below that better fits your positive thoughts about your current or last work experience:',
 17:'17. Select the options below that better fits your negative thoughts about your current or last work experience:',
 18:'18. Do you feel that your University studies matches with what you aspirated?',
 19:'19. Did you take another specialization course/MBA/Phd/Bootcamp?',
 20:'20. If yes, what was the course/MBA/Phd/Bootcamp? And Why?',
 21:'21. Do you feel that you need/had to change career to have more work opportunities? '}, inplace=True)

In [88]:
survey.to_excel("Survey_Cor_Questions.xlsx", index=False)